### ISSUE TITLE
contributing file

### ISSUE THREAD

**Issue by HeladoDeBrownie** [HeladoDeBrownie/tiny-terrarium#14]
write a contributing file

**Comment by the-amazing-atharva** [comment]
Hey,

If it's ok, I would like to add a general contributing file !

**Comment by HeladoDeBrownie** [comment]
i appreciate the offer, but ironically i'd like to decide what the contributing file should look like before accepting any contributions!

**Comment by the-amazing-atharva** [comment]
No worries!

**Comment by HeladoDeBrownie** [comment]
resolved by b1ee980ebc647f447956ba0942b3137958e7cc10
